# Basic
title: 深度学习俱乐部
subtitle: 个人深度学习的博客
welcome_message: <a href="https://github.com/JonyZeng/JonyZeng.github.io" target="_blank">进入我的GitHub</a>
description: 深度学习俱乐部，和大家一起打上人工智能的末班车。欢迎大家一起研究学习
creator: <a href="http://www.deeplearningclub.cn">JonyZ</a>

url: "http://www.deeplearningclub.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: JonyZ blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/JonyZeng/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: JonyZ
    github: JonyZeng
    twitter: JonyZ
    gplus: 107108267983477358170
    mail: prodigalzq@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
